name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd searcher && go build .
      
      - name: Test Searcher
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd searcher && go test -v -cover -race .

      - name: Test test article server
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd server-test-articles && go test -v -cover -race .

  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: diff -u <(echo -n) <(gofmt -d .)

  
